version: '3.1'

services:
  db:
    container_name: database
    image: sameersbn/postgresql:10-2
    env_file:
       - ".env"
    environment:
      DB_PASS: $DB_PASS
    restart: always
    ports:
      - 5432:5432
    networks:
      - botnet
    volumes:
      - ./postgres:/var/lib/postgresql

  tgbot:
    container_name: bot
    build:
      context: .
    command: python bot.py
    networks:
      - botnet
    restart: always
    env_file:
      - ".env"
    volumes:
      - .:/src
    depends_on:
      - db

networks:
  botnet:
    driver: bridge