version: "3"
services:
  bot:
      build: .
      command: >
        sh -c "python bot.py"



      environment:
        DB_HOST: "postgres"
        DB_PORT: "5432"
        DB_NAME: "gemini_bot"
        DB_USER: "postgres"
        DB_PASS: "24651asd"
      restart: always

      volumes:
          - .:/src


networks:
  postgres:
    driver: bridge
